### PR TITLE
Nacent reorganisation structure

### PR DESCRIPTION
**Pull request by Fr-Dae**

### CODE REVIEW

**Comment by Fr-Dae** [comment]
@mortifia review need

**Review by GemInee — COMMENTED** [review]
It doesn't work for me.
The language switching still doesn't work.
What's the point of PR?

**Comment by Nacent** [comment]
I just start learning Mkdocs
so I thinking this method was a first answer 
to make language switching work

**Comment by Fr-Dae** [comment]
@Clemy-beep peux tu nous aidé sur la review de cette branche svp ?

**Review by mortifia — APPROVED** [review]
tmp

**Comment by Fr-Dae** [comment]
@mortifia rappel Lundi

**Pull request merged**
